serverAddress: ":80"
storageHost: "http://5b0e-82-12-154-226.ngrok.io"
environment: dev
embedStaticFiles: true
useInClusterConfig: false
sentryDsn: https://0b5bb19136ee423783dd3c2b48ab3594@o58538.ingest.sentry.io/5960484
databaseDsn: postgres://app:password@localhost:5444/app?sslmode=disable
manifest: https://raw.githubusercontent.com/aptenex/k8-store/main/manifest.yaml
kubernetes:
  labelSelector: app.kubernetes.io/name=wordpress
logging:
  level: debug