serverAddress: ":8999"
storageHost: wpcmd.eu.ngrok.io
environment: dev
embedStaticFiles: false
useInClusterConfig: false
mailgun:
  from:
  domain:
  baseUrl:
  apiKey:
sentryDsn:
databaseDsn: postgres://app:password@localhost:5445/app_test?sslmode=disable
manifest: https://raw.githubusercontent.com/aptenex/k8-store/main/manifest.yaml
githubToken:
github:
  owner: aptenex
  repo: rentivo-gatsby-themes
  previewWorkflow: dynamic_preview.yaml
docker:
  namespace: samrentivo
  previewRepo: preview
kubernetes:
  labelSelector: app.kubernetes.io/name=wordpress
logging:
  level: debug