serverAddress: ":8999"
storageHost: wpcmd.eu.ngrok.io
environment: dev
embedStaticFiles: false
useInClusterConfig: false
mailgun:
  from: "Rentivo Build <build@rentivo.com>"
  domain: manage.rentivo.com
  baseUrl: https://api.eu.mailgun.net/v3
  apiKey:
sentryDsn:
databaseDsn: postgres://app:password@wpcmd_postgres:5432/app_test?sslmode=disable
manifest: https://raw.githubusercontent.com/aptenex/k8-store/main/manifest.yaml
wpcmdAccessToken:
githubToken:
github:
  owner: aptenex
  repo: rentivo-gatsby-themes
  previewWorkflow: dynamic_preview.yaml
docker:
  namespace: samrentivo
  previewRepo: preview
kubernetes:
  labelSelector: app.kubernetes.io/name=wordpress
logging:
  level: warn