serverAddress: ":8999"
storageHost: https://wpcmd.k8.rentivo.com
environment: dev
embedStaticFiles: true
useInClusterConfig: true
sentryDsn:
databaseDsn:
manifest: https://raw.githubusercontent.com/aptenex/k8-store/main/manifest.yaml
githubToken:
github:
  owner: aptenex
  repo: rentivo-gatsby-themes
  previewWorkflow: dynamic_preview.yaml
docker:
  namespace: samrentivo
kubernetes:
  labelSelector: app.kubernetes.io/name=wordpress
logging:
  level: warn