serverAddress: ":8999"
storageHost: wpcmd.k8.rentivo.com
environment: dev
embedStaticFiles: true
useInClusterConfig: true
sentryDsn:
databaseDsn:
manifest: https://raw.githubusercontent.com/aptenex/k8-store/main/manifest.yaml
kubernetes:
  labelSelector: app.kubernetes.io/name=wordpress
logging:
  level: warn