version: '3.7'

volumes:
  postgres_data:
  redis_data:

services:
  postgres:
    image: postgres:latest
    ports:
      - 5444:5432
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    volumes:
      - ./docker/db-data/:/var/lib/postgresql/data/

  postgres_test:
    image: postgres:latest
    ports:
      - 5445:5432
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_test

  redis:
    image: redis:latest
    ports:
      - 6378:6379
    volumes:
      - ./docker/redis/data:/data
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master