version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.16.9
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: make test-integration-ci
      - run:
          name: List running containers
          command: docker container ls
      - store_test_results:
          path: /tmp/test-reports

workflows:
  build:
    jobs:
      - build
