version: 2.1

jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Start docker-compose services and run tests
          command: make docker-up-ci
      - store_test_results:
          path: /tmp/test-reports

workflows:
  build:
    jobs:
      - build
