### Create Command Job
POST http://localhost:8999/api/command/job
Content-Type: application/json
Token: {{token}}

{
  "CommandId": 31,
  "Selector": "demo-wp"
}

### Create Command Job
POST http://localhost:8999/api/command/job
Content-Type: application/json
Token: {{token}}

{
  "Command": "setup-fresh-install",
  "Selector": "demo-wp"
}